[tasks.actions]
run = '''
set -xeuo pipefail

gh run watch || true
gh run download --name firmware
mv *left.uf2 ~/Desktop/left.uf2 && mv *right.uf2 ~/Desktop/right.uf2
'''

[tasks.make]
run = '''
set -xeuo pipefail

rm firmware/*.uf2 || true
make all
mv firmware/*left.uf2 ~/Desktop/left.uf2 && mv firmware/*right.uf2 ~/Desktop/right.uf2
'''
