version: 3

tasks:
  actions:
    - gh run watch
    - gh run download --name firmware
    - mv *left.uf2 ~/Desktop/left.uf2 && mv *right.uf2 ~/Desktop/right.uf2

  make:
    - rm firmware/*.uf2 || true
    - make all
    - mv firmware/*left.uf2 ~/Desktop/left.uf2 && mv firmware/*right.uf2 ~/Desktop/right.uf2
